# 2010-03-17  Michele Tavella <michele.tavella@epfl.ch>
# Needed just if your environment is not properly configured
#INCPATH=-I/homes/mtavella/Build/include/ 
#LIBPATH=-L/homes/mtavella/Build/lib/ 

# Which library are we linking against?
PROJECT=tobiid
LIBNAME=lib$(PROJECT)
LDSTUFF=-l$(PROJECT) -ltobicore
SOURCE_MW=$(PROJECT).mw
SOURCE_CC=$(PROJECT).cc

# Select platform
PLATFORM=$(shell echo -n `uname -s`)

all: $(PROJECT)

$(PROJECT): $(SOURCE_MW)
	@echo "Building and compiling the $(LIBNAME) MEX wrapper"
	@echo "Platform is: $(PLATFORM)"
	@echo "Generating wrapper file with MWrap"
	@mwrap -mex $(PROJECT) \
		-c $(SOURCE_CC) \
		-mb $(SOURCE_MW)
ifeq ($(PLATFORM), Linux)
	@echo "Calling Matlab MEX"
	@mex -largeArrayDims $(INCPATH) $(LIBPATH) $(LDSTUFF) $(SOURCE_CC)
else
	@echo "Please run make.m from Matlab/GNUMex"
endif

clean:
	@rm -vf *.mex*
	@rm -vf *.cc
	@rm -vf idmessage_*.m
	@rm -vf idserializerrapid_*.m
	@rm -vf idasclient*.m
	@rm -vf core

local-install:
	@mkdir -p ${CNBITK_MATLAB}/mex${PROJECT}/
	@cp -vf *.mex* ${CNBITK_MATLAB}/mex${PROJECT}/
	@cp -vf idmessage_*.m ${CNBITK_MATLAB}/mex${PROJECT}/
	@cp -vf idasclient*.m ${CNBITK_MATLAB}/mex${PROJECT}/
	@cp -vf idserializerrapid_*.m ${CNBITK_MATLAB}/mex${PROJECT}/
	@cp -vf example_*.m ${CNBITK_MATLAB}/mex${PROJECT}/

install:
	@mkdir -p /opt/cnbitkmat/mex${PROJECT}/
	@cp -vf *.mex* /opt/cnbitkmat/mex${PROJECT}/
	@cp -vf idmessage_*.m /opt/cnbitkmat/mex${PROJECT}/
	@cp -vf idasclient*.m /opt/cnbitkmat/mex${PROJECT}/
	@cp -vf idserializerrapid_*.m /opt/cnbitkmat/mex${PROJECT}/
	@cp -vf example_*.m /opt/cnbitkmat/mex${PROJECT}/
